### ISSUE TITLE
[Feature] ci yml action优化

### ISSUE THREAD

**Issue by supperthomas** [RT-Thread/rt-thread#10051]
### Describe problem solved by the proposed feature

- [ ] yml有些配置比较耗时间，可否帮忙整理一下yml的配置，删除一些没有意义的重复的配置。
- [ ] 希望bsp中的yml能尽量放一些常用的bsp相关的配置，重点优化：RTduino/Arduino Libraries (Raspberry Pico) 和stm32l4
- [ ] RTduino/Arduino Libraries (STM32F412 Nucleo) 和RTduino/Arduino Libraries (Raspberry Pico) 有一些重复，保留RTduino/Arduino Libraries (Raspberry Pico)中有效的配置即可。

### Describe your preferred solution

![Image](https://github.com/user-attachments/assets/a084c6b8-ac12-483a-92c1-95e48562e9bd)

_No response_

**Comment by supperthomas** [comment]
查看PR差异文件路径
```
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
```
