### ISSUE TITLE
[Feature] [risc-v] RISC-V 的toolchain 讨论

### ISSUE THREAD

**Issue by supperthomas** [RT-Thread/rt-thread#10161]
### Describe problem solved by the proposed feature

目前RISC-V的toolchain版本比较多，这里加一些讨论，讨论哪些toolchain版本是比较通用和官方的，方便后续RISC-V平台整理和使用比较统一的版本。
大家可以提供一些自己常用的RISCV的toolchain的下载路径和RISCV平台的详细信息。

**Comment by supperthomas** [comment]
https://github.com/riscv-collab/riscv-gnu-toolchain/releases

这个是RISCV的版本

**Comment by supperthomas** [comment]
https://github.com/xpack-dev-tools/riscv-none-elf-gcc-xpack/releases

这个是XPACK的版本

**Comment by supperthomas** [comment]
```yml
riscv-none-embed-gcc:
  bsp:
  - gd32/risc-v/gd32vf103r-start
  - gd32/risc-v/gd32vf103v-eval
  - hifive1
  - juicevm
  - k210
  - rv32m1_vega/ri5cy
  - wch/risc-v/ch32v103r-evt
  - wch/risc-v/ch32v208w-r0
  - wch/risc-v/ch32v307v-r1
  - wch/risc-v/ch569w-evt
  - wch/risc-v/yd-ch32v307vct6
  count: 11
  download_url: https://github.com/RT-Thread/toolchains-ci/releases/download/v1.5/xpack-riscv-none-embed-gcc-8.3.0-2.3-linux-x64.tar.gz
riscv-nuclei-elf-gcc:
  bsp:
  - nuclei/gd32vf103_rvstar
  - nuclei/nuclei_fpga_eval
  count: 2
riscv32-esp-elf-gcc:
  bsp:
  - ESP32_C3
  count: 1
  download_url: https://github.com/espressif/crosstool-NG/releases/download/esp-2022r1-RC1/riscv32-esp-elf-gcc11_2_0-esp-2022r1-RC1-linux-amd64.tar.xz
riscv32-unknown-elf-gcc:
  bsp:
  - core-v-mcu/core-v-cv32e40p
  - hpmicro/hpm5300evk
  - hpmicro/hpm5301evklite
  - hpmicro/hpm6200evk
  - hpmicro/hpm6300evk
  - hpmicro/hpm6750evk
  - hpmicro/hpm6750evk2
  - hpmicro/hpm6750evkmini
  - hpmicro/hpm6800evk
  count: 9
  download_url: https://github.com/hpmicro/riscv-gnu-toolchain/releases/download/2022.05.15/riscv32-unknown-elf-newlib-multilib_2022.05.15_linux.tar.gz
riscv64-unknown-elf-gcc:
  bsp:
  - bluetrum/ab32vg1-ab-prougen
  - bouffalo_lab/bl60x
  - bouffalo_lab/bl61x
  - bouffalo_lab/bl70x
  - bouffalo_lab/bl808/lp
  - bouffalo_lab/bl808/m0
  - cvitek/c906_little
  - cvitek/cv18xx_risc-v
  - qemu-virt64-riscv
  - sparkfun-redv
  - thead-smart
  count: 11
  download_url: https://github.com/RT-Thread/toolchains-ci/releases/download/v1.4/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz
riscv64-unknown-linux-musl-gcc:
  bsp:
  - allwinner/d1
  - allwinner/d1s
  - bouffalo_lab/bl808/d0
  count: 3
sparc-gaisler-elf-gcc:
  bsp:
  - bm3803
  count: 1
unicore32-linux-gcc:
  bsp:
  - sep6200
  count: 1
```
