### ISSUE TITLE
[Feature] ci/cd 在qemu上实现方案

### ISSUE THREAD

**Issue by supperthomas** [RT-Thread/rt-thread#9937]
### Describe problem solved by the proposed feature

可以在原有的ci.attachconfig.yml中实现如下规则：

```yml
bsp_board_info:
    arch: arm
    toolchain: arm-none-eabi-gcc
    pre_build:
       ./tools/ci/toolchain.sh arm-none-eabi-gcc
      apt-get install qemu-system
    post_build: objcopy rtthread.elf rtthread.hex
    run_cmd: ./qemu-nographic.sh
    qemu_flag: true
pkg.tools.coremark:
  kconfig: 
    - CONFIG_PKG_USING_COREMARK=y
  ci_build_run_flag : true
  checkresult: '[==========] [ utest ] end'
```

### Describe your preferred solution

```yml
bsp_board_info:
    arch: arm
    toolchain: arm-none-eabi-gcc
    pre_build:
       ./tools/ci/toolchain.sh arm-none-eabi-gcc
      apt-get install qemu-system
    post_build: objcopy rtthread.elf rtthread.hex
    run_cmd: ./qemu-nographic.sh
    qemu_flag: true
pkg.tools.coremark:
  kconfig: 
    - CONFIG_PKG_USING_COREMARK=y
  ci_build_run_flag : true
  checkresult: '[==========] [ utest ] end'
```
